export const LEAD_SOURCES = {
  META: 'META',
  FACEBOOK: 'FACEBOOK',
  INSTAGRAM: 'INSTAGRAM',
  WHATSAPP: 'WHATSAPP',
  CALL: 'CALL',
  WEBSITE: 'WEBSITE',
  WALKIN: 'WALKIN',
  REFERRAL: 'REFERRAL',
  MANUAL: 'MANUAL',
  OTHER: 'OTHER'
};

export const LEAD_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  FOLLOW_UP: 'FOLLOW_UP',
  INTERESTED: 'INTERESTED',
  QUALIFIED: 'QUALIFIED',
  ORDER_CREATED: 'ORDER_CREATED',
  CONVERTED: 'CONVERTED',
  NOT_INTERESTED: 'NOT_INTERESTED',
  INVALID: 'INVALID',
  LOST: 'LOST'
};

export const CALL_STATUS = {
  INTERESTED: 'INTERESTED',
  CONNECTED_INTERESTED: 'CONNECTED_INTERESTED',
  CONNECTED_CALLBACK_REQUESTED: 'CONNECTED_CALLBACK_REQUESTED',
  CONNECTED_NOT_INTERESTED: 'CONNECTED_NOT_INTERESTED',
  NO_ANSWER: 'NO_ANSWER',
  BUSY: 'BUSY',
  CALL_LATER: 'CALL_LATER',
  FOLLOW_UP_REQUIRED: 'FOLLOW_UP_REQUIRED',
  NOT_INTERESTED: 'NOT_INTERESTED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  INVALID_NUMBER: 'INVALID_NUMBER',
  SWITCHED_OFF: 'SWITCHED_OFF',
  WRONG_NUMBER: 'WRONG_NUMBER'
};

export const FOLLOWUP_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

export const FOLLOWUP_CATEGORIES = {
  TODAY: 'TODAY',
  OVERDUE: 'OVERDUE',
  UPCOMING: 'UPCOMING',
  COMPLETED: 'COMPLETED',
  MISSED: 'MISSED'
};
