export const ORDER_STATUS = {
  NEW: 'NEW',
  CONFIRMED: 'CONFIRMED',
  PROCESSING: 'PROCESSING',
  READY_FOR_PACKING: 'READY_FOR_PACKING',
  PACKED: 'PACKED',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  DISPATCHED: 'DISPATCHED',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RTO: 'RTO'
};

// Strict state transition graph
export const ALLOWED_ORDER_TRANSITIONS = {
  [ORDER_STATUS.NEW]: [ORDER_STATUS.CONFIRMED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.CONFIRMED]: [ORDER_STATUS.PROCESSING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PROCESSING]: [ORDER_STATUS.READY_FOR_PACKING, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_PACKING]: [ORDER_STATUS.PACKED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.PACKED]: [ORDER_STATUS.READY_FOR_DISPATCH, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.READY_FOR_DISPATCH]: [ORDER_STATUS.DISPATCHED, ORDER_STATUS.CANCELLED],
  [ORDER_STATUS.DISPATCHED]: [ORDER_STATUS.IN_TRANSIT, ORDER_STATUS.DELIVERY_FAILED, ORDER_STATUS.RTO],
  [ORDER_STATUS.IN_TRANSIT]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.DELIVERY_FAILED, ORDER_STATUS.RTO],
  [ORDER_STATUS.OUT_FOR_DELIVERY]: [ORDER_STATUS.DELIVERED, ORDER_STATUS.DELIVERY_FAILED, ORDER_STATUS.RTO],
  [ORDER_STATUS.DELIVERY_FAILED]: [ORDER_STATUS.OUT_FOR_DELIVERY, ORDER_STATUS.RTO],
  [ORDER_STATUS.RTO]: [], // terminal state in orders, further handled by RTO module
  [ORDER_STATUS.DELIVERED]: [], // terminal state
  [ORDER_STATUS.CANCELLED]: [] // terminal state
};
