export const PERMISSIONS = {
  // Leads
  LEADS_VIEW: 'leads.view',
  LEADS_CREATE: 'leads.create',
  LEADS_EDIT: 'leads.edit',
  LEADS_ASSIGN: 'leads.assign',
  LEADS_REASSIGN: 'leads.reassign',
  LEADS_DELETE: 'leads.delete',

  // Follow-ups
  FOLLOWUPS_VIEW: 'followups.view',
  FOLLOWUPS_CREATE: 'followups.create',
  FOLLOWUPS_EDIT: 'followups.edit',
  FOLLOWUPS_COMPLETE: 'followups.complete',

  // Customers
  CUSTOMERS_VIEW: 'customers.view',
  CUSTOMERS_CREATE: 'customers.create',
  CUSTOMERS_EDIT: 'customers.edit',

  // Orders
  ORDERS_VIEW: 'orders.view',
  ORDERS_CREATE: 'orders.create',
  ORDERS_EDIT: 'orders.edit',
  ORDERS_DELETE: 'orders.delete',
  ORDERS_VERIFY: 'orders.verify',
  ORDERS_PROCESS: 'orders.process',
  ORDERS_PACK: 'orders.pack',
  ORDERS_DISPATCH: 'orders.dispatch',
  ORDERS_CANCEL: 'orders.cancel',

  // Products & Inventory
  PRODUCTS_VIEW: 'products.view',
  PRODUCTS_CREATE: 'products.create',
  PRODUCTS_EDIT: 'products.edit',
  INVENTORY_VIEW: 'inventory.view',
  INVENTORY_MANAGE: 'inventory.manage',
  INVENTORY_ADJUST: 'inventory.adjust',
  INVENTORY_TRANSFER: 'inventory.transfer',

  // Operations & Shipping
  OPERATIONS_VIEW: 'operations.view',
  SHIPPING_VIEW: 'shipping.view',
  SHIPPING_MANAGE: 'shipping.manage',
  DELIVERY_VIEW: 'delivery.view',
  DELIVERY_MANAGE: 'delivery.manage',

  // RTO
  RTO_VIEW: 'rto.view',
  RTO_MANAGE: 'rto.manage',
  RTO_VERIFY: 'rto.verify',

  // Reports
  REPORTS_VIEW: 'reports.view',
  REPORTS_EXPORT: 'reports.export',

  // User & System Administration
  USERS_VIEW: 'users.view',
  USERS_CREATE: 'users.create',
  USERS_EDIT: 'users.edit',
  USERS_DISABLE: 'users.disable',
  ROLES_MANAGE: 'roles.manage',
  PERMISSIONS_MANAGE: 'permissions.manage',
  BRANCHES_MANAGE: 'branches.manage',
  SETTINGS_MANAGE: 'settings.manage',
  INTEGRATIONS_MANAGE: 'integrations.manage',
  AUDIT_VIEW: 'audit.view'
};

export const DEFAULT_ROLE_PERMISSIONS = {
  OWNER: Object.values(PERMISSIONS),
  
  DISTRIBUTOR: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.SHIPPING_VIEW,
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.RTO_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT
  ],

  MANAGER: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.LEADS_ASSIGN,
    PERMISSIONS.LEADS_REASSIGN,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.ORDERS_VERIFY,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.ORDERS_PACK,
    PERMISSIONS.ORDERS_DISPATCH,
    PERMISSIONS.ORDERS_CANCEL,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.PRODUCTS_CREATE,
    PERMISSIONS.PRODUCTS_EDIT,
    PERMISSIONS.INVENTORY_VIEW,
    PERMISSIONS.INVENTORY_MANAGE,
    PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.SHIPPING_VIEW,
    PERMISSIONS.SHIPPING_MANAGE,
    PERMISSIONS.DELIVERY_VIEW,
    PERMISSIONS.DELIVERY_MANAGE,
    PERMISSIONS.RTO_VIEW,
    PERMISSIONS.RTO_MANAGE,
    PERMISSIONS.RTO_VERIFY,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.USERS_VIEW
  ],

  TELECALLER: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE,
    PERMISSIONS.FOLLOWUPS_VIEW,
    PERMISSIONS.FOLLOWUPS_CREATE,
    PERMISSIONS.FOLLOWUPS_EDIT,
    PERMISSIONS.FOLLOWUPS_COMPLETE,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.CUSTOMERS_CREATE,
    PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.ORDERS_VIEW,
    PERMISSIONS.ORDERS_CREATE,
    PERMISSIONS.ORDERS_EDIT,
    PERMISSIONS.ORDERS_DELETE,
    PERMISSIONS.ORDERS_PROCESS,
    PERMISSIONS.PRODUCTS_VIEW,
    PERMISSIONS.SHIPPING_VIEW,
    PERMISSIONS.DELIVERY_VIEW
  ]
};
