export const ROLES = {
  OWNER: 'OWNER',
  DISTRIBUTOR: 'DISTRIBUTOR',
  MANAGER: 'MANAGER',
  TELECALLER: 'TELECALLER'
};

export const ROLE_HIERARCHY = {
  [ROLES.OWNER]: 100,
  [ROLES.DISTRIBUTOR]: 75,
  [ROLES.MANAGER]: 50,
  [ROLES.TELECALLER]: 25
};
