export const SHIPPING_STATUS = {
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  PICKUP_SCHEDULED: 'PICKUP_SCHEDULED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  RTO_INITIATED: 'RTO_INITIATED',
  RTO_IN_TRANSIT: 'RTO_IN_TRANSIT',
  RTO_RECEIVED: 'RTO_RECEIVED'
};

export const COURIER_PROVIDERS = {
  INDIA_POST: 'INDIA_POST',
  PROFESSIONAL_COURIER: 'PROFESSIONAL_COURIER',
  CUSTOM_COURIER: 'CUSTOM_COURIER'
};

export const RTO_REASONS = {
  CUSTOMER_REFUSED: 'CUSTOMER_REFUSED',
  ADDRESS_ISSUE: 'ADDRESS_ISSUE',
  UNREACHABLE: 'UNREACHABLE',
  DELIVERY_FAILED: 'DELIVERY_FAILED',
  DAMAGED_IN_TRANSIT: 'DAMAGED_IN_TRANSIT',
  OTHER: 'OTHER'
};

export const RTO_CONDITION = {
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
  SALEABLE: 'SALEABLE',
  DAMAGED: 'DAMAGED',
  MISSING: 'MISSING',
  PARTIALLY_RETURNED: 'PARTIALLY_RETURNED'
};
