export const STOCK_STATES = {
  AVAILABLE: 'AVAILABLE',
  RESERVED: 'RESERVED',
  ALLOCATED: 'ALLOCATED',
  DISPATCHED: 'DISPATCHED',
  RETURNED: 'RETURNED',
  DAMAGED: 'DAMAGED'
};

export const MOVEMENT_TYPES = {
  IN: 'IN',
  OUT: 'OUT',
  RESERVE: 'RESERVE',
  RELEASE: 'RELEASE',
  TRANSFER_OUT: 'TRANSFER_OUT',
  TRANSFER_IN: 'TRANSFER_IN',
  RETURN: 'RETURN',
  DAMAGE: 'DAMAGE',
  ADJUSTMENT: 'ADJUSTMENT'
};

export const MOVEMENT_REASONS = {
  PURCHASE: 'PURCHASE',
  ORDER_RESERVATION: 'ORDER_RESERVATION',
  ORDER_DISPATCH: 'ORDER_DISPATCH',
  ORDER_CANCELLATION: 'ORDER_CANCELLATION',
  STOCK_TRANSFER: 'STOCK_TRANSFER',
  RTO_RETURN: 'RTO_RETURN',
  DAMAGED: 'DAMAGED',
  EXPIRED: 'EXPIRED',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
  PHYSICAL_AUDIT: 'PHYSICAL_AUDIT'
};

export const TRANSFER_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  IN_TRANSIT: 'IN_TRANSIT',
  RECEIVED: 'RECEIVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};
